#!/usr/bin/env python3
"""Create the deterministic synthetic NetCDF archive used by the direct-delivery demo."""
from __future__ import annotations

import argparse
import hashlib
import logging
from pathlib import Path

import numpy as np
import xarray as xr

LOGGER = logging.getLogger(__name__)
STAMP = "20260907Z1200"


def build(root: Path) -> Path:
    """Write one fixed CF-style frame under the normative archive hierarchy."""
    target = (root / "demo_weather" / "d01" / "archive" / "2026" / "09" / "07" /
              f"demo_weather_d01_{STAMP}.nc")
    target.parent.mkdir(parents=True, exist_ok=True)
    latitude = np.linspace(35.0, 47.0, 49, dtype=np.float64)
    longitude = np.linspace(5.0, 20.0, 61, dtype=np.float64)
    lon_grid, lat_grid = np.meshgrid(longitude, latitude)
    temperature = (18.0 - 0.55 * (lat_grid - 35.0) + 0.08 * (lon_grid - 5.0)).astype(np.float32)
    wind = (3.0 + 0.12 * (lat_grid - 35.0) + 0.04 * (lon_grid - 5.0)).astype(np.float32)
    dataset = xr.Dataset(
        {
            "air_temperature": (
                ("time", "latitude", "longitude"), temperature[None, :, :],
                {"units": "degC", "long_name": "Synthetic near-surface air temperature"},
            ),
            "wind_speed": (
                ("time", "latitude", "longitude"), wind[None, :, :],
                {"units": "m s-1", "long_name": "Synthetic near-surface wind speed"},
            ),
        },
        coords={
            "time": ("time", np.array([0.0]), {"units": "hours since 2026-09-07 12:00:00 UTC"}),
            "latitude": ("latitude", latitude, {"units": "degrees_north", "standard_name": "latitude"}),
            "longitude": ("longitude", longitude, {"units": "degrees_east", "standard_name": "longitude"}),
        },
        attrs={
            "title": "DataTiles direct NetCDF delivery synthetic fixture",
            "source": "deterministic analytic fields generated by demo/netcdf-archive/prepare.py",
            "geospatial_bounds_crs": "EPSG:4326",
            "license": "CC0-1.0",
            "limitations": "Synthetic software demonstration; not observational data and not for navigation.",
        },
    )
    dataset.to_netcdf(target, mode="w")
    digest = hashlib.sha256(target.read_bytes()).hexdigest()
    LOGGER.info("Created %s", target)
    LOGGER.info("SHA-256 %s", digest)
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("data/netcdf-archive-demo"))
    args = parser.parse_args()
    build(args.root.expanduser().resolve())
    return 0


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    raise SystemExit(main())
